package bg.persistence.tool.hibernate;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement(name = "entity-mappings")
public class HibernateMapping {

	private List<HibernateClass> listClass = new ArrayList<>();
	@XmlAttribute(name = "xmlns")
	private String xmlns = "http://java.sun.com/xml/ns/persistence/orm";
	
	@XmlAttribute(name = "xmlns:xsi")
	private String xmlns_xsi = "http://www.w3.org/2001/XMLSchema-instance";

	@XmlAttribute(name = "xsi:schemaLocation")
	private String xsi_schemaLocation = "http://java.sun.com/xml/ns/persistence/orm http://java.sun.com/xml/ns/persistence/orm_1_0.xsd";

	@XmlAttribute(name = "version")
	private String version="1.0";

	String packageStr;
	 
	@XmlElement(name = "description")
	String description ="Mapping hibernate generated by tool";
	
	@XmlElement(name = "entity")
	public List<HibernateClass> getListClass() {
		return listClass;
	}

	public void setListClass(List<HibernateClass> listClass) {
		this.listClass = listClass;
	}

	public void setPackageStr(String packageStr) {
		this.packageStr = packageStr;
	}

}
